apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-consumer-api
  name: location-consumer-api
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    service: location-consumer-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-consumer-api
  name: location-consumer-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-consumer-api
  template:
    metadata:
      labels:
        service: location-consumer-api
    spec:
      containers:
      - image: imthiyagu/location-consumer-svc:latest
        name: location-consumer-api
        imagePullPolicy: Always
        env:
        - name: KAFKA_CONSUMER
          valueFrom:
            configMapKeyRef:
              name: kafka-location-consumer-map
              key: KAFKA_CONSUMER
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: kafka-location-consumer-map
              key: KAFKA_TOPIC
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: kafka-location-consumer-map
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: kafka-location-consumer-map
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: kafka-location-consumer-map
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: kafka-location-consumer-map
              key: DB_PORT
      restartPolicy: Always